const TRANSFER_FILTERS_CHECK = 'TRANSFER_FILTERS_CHECK';
const TRANSFER_FILTERS_CHECK_ALL = 'TRANSFER_FILTERS_CHECK_ALL';
const MOST_FILTERS_CHECK = 'MOST_FILTERS_CHECK';

export { TRANSFER_FILTERS_CHECK, TRANSFER_FILTERS_CHECK_ALL, MOST_FILTERS_CHECK };
