const TRANSFER_FILTERS_CHECK = 'TRANSFER_FILTERS_CHECK';
const TRANSFER_FILTERS_CHECK_ALL = 'TRANSFER_FILTERS_CHECK_ALL';

const MOST_FILTERS_CHECK = 'MOST_FILTERS_CHECK';

const GET_SEARCH_ID_REQUEST = 'GET_SEARCH_ID_REQUEST';
const GET_SEARCH_ID_SUCCESS = 'GET_SEARCH_ID_SUCCESS';

const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';

export {
  TRANSFER_FILTERS_CHECK,
  TRANSFER_FILTERS_CHECK_ALL,
  MOST_FILTERS_CHECK,
  GET_SEARCH_ID_REQUEST,
  GET_SEARCH_ID_SUCCESS,
  GET_TICKETS_REQUEST,
  GET_TICKETS_SUCCESS,
};
